###################  项目启动端口  ###################
server:
  port: 8082
  context-path: /
  tomcat:
    uri-encoding: UTF-8
# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.fhs.basics.dox;
eureka:
  instance:
    hostname: eureka.fhs.xhb.com
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:20881/eureka/
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


fhs:
  autoware:
    package: com.fhs.*;com.fhs.*.*;
  login:
    #是否开启cas默认关闭
    enable-cas: true
    cas:
      shiroServerUrlPrefix: http://localhost:8082/
      loginUrl: http://114.115.211.214/cas?service=${shiro.cas.shiroServerUrlPrefix}/shiro-cas
  mybatis-jpa:
    #多个用;分隔
    entity-package: com.**.**.dox
    mapper-package: com.**.**.mapper
  safe:
    enable-xss: true #xss注入控制
  session:
    timeout: 1800
  task:
    default-lock-Minutes: 10
    pool-size: 10
  transcatoin: #声明式事物 类名包含service的，但是不包含api，action,dao的类开启
    contains: service
    not-contains: api;controller;mapper
    #声明式事物管理，具体请访问官网
    package: com.fhs;
  cache: #CacheUpdateManager 支持缓存包扫码
    packages: com.fhs.**.service.impl
  disable-apollo: true
  swagger: # ip:port/doc.html 是swagger-ui的地址,本插件用的是swagger-bootstrap-ui
    enable: false
    basepackage: com.fhs
    service:
      description: 项目api
      developer: fhs developers
      name: 公共接口文档
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: fhs_admin_app
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 10
    host: 172.16.57.109
    port: 6379
    timeout: 6000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 20
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    name: base_business
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: trueserver
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.16.57.109:3306/fhs-demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    validationQuery: select 'x'




logging:
  config: classpath:logback-spring.xml
  level:
    com.fhs.basics: debug
    com.fhs.pagex: debug

logback:
  #这里可以配置logstash ip和端口
  elk:
    host: 172.16.57.109:9250
  root:
    level: INFO
  file:
    #日志存放路径
    dir: c:/logs/base/

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.alibaba
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
  remote: #阿里的jetcache2级缓存
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri:
        - redis://172.16.57.109:6379/1  #redis://密码@IP:端口/库